channels:
        - conda-forge
dependencies:
        - appmode
        - python
        - numpy
        - scipy 
        - pandas
        - holoviews
        - bokeh
        - matplotlib
        - jupyter
                
