channels:
        - conda-forge
dependencies:
        - appmode
        - python
        - numpy
        - pip
        - pip:
                - pandas
                - holoviews
                - bokeh
                
